[workspace]
members = ["build/parry2d", "build/parry3d", "build/parry2d-f64", "build/parry3d-f64"]

[patch.crates-io]
parry2d = { path = "build/parry2d" }
parry3d = { path = "build/parry3d" }
parry2d-f64 = { path = "build/parry2d-f64" }
parry3d-f64 = { path = "build/parry3d-f64" }
